theme: jekyll-theme-minimal
title: Amit's Homepage
description: Bookmark my page to keep tabs on the latest news in transportation and geotechnical asset management. Also check out some of the projects from numerical methods class at Texas A&M. This page is currently under construction now. 
